### ISSUE TITLE
Crashes to report

### ISSUE THREAD

**Issue by jamestagal** [plenti-themes/fitlife#2]
Hi @jimafisk 

I have been looking at this theme since you pushed updates and I have learnt a few things such as how you have added components into the schema and used a `meta` data info and date picker and other things.  :) It's been really useful for me to learn how you have added features. 

But while looking around I have had some crashed. I have updated to the latest version of Plenti v0.6.9 and noticed the builds are really fast much faster that when running say the Educenter site locally. For instance the ```total build``` is only about 1.2 secs compared to 2 sec on the former.  But what is strange is that when I click around in the files, so I mean click on a file in the opened project in VS code it triggers a `build`. This behaviour doesn't happen while I am working in the Educenter project. :) Often when I saving changes in this project the build only seems to crash on svelte file saves (not when saving json changes) and I think i have posted that one before but here it is again.

This is the crash log in `Educenter` theme after saving a `svelte` file.
```terminal
Could not compile 'core/cms/admin_menu.svelte' Svelte component: Unable to write compiled client file: open public/spa/core/cms/admin_menu.js: no such file or directory
2023/04/22 09:43:00 build.go:115: 
Can't remove "%v" folder from previous buildunlinkat ./public: directory not emptypublic

```

Anyway, I have had a few crashes and wanted to post them here for your reference:
These logs are from `Fitlife` theme. 
<details><summary>First crash log </summary>

```terminal
<--- Last few GCs --->


<--- JS stacktrace --->


#
# Fatal javascript OOM in GC during deserialization
#

SIGTRAP: trace trap
PC=0x100c28364 m=4 sigcode=0
signal arrived during cgo execution

goroutine 50 [syscall]:
runtime.cgocall(0x100c06874, 0x140005bd728)
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/cgocall.go:157 +0x54 fp=0x140005bd6f0 sp=0x140005bd6b0 pc=0x1006e2934
rogchap.com/v8go._Cfunc_NewIsolate()
        _cgo_gotypes.go:734 +0x3c fp=0x140005bd720 sp=0x140005bd6f0 pc=0x1009c16bc
rogchap.com/v8go.NewIsolate()
        /home/runner/go/pkg/mod/rogchap.com/v8go@v0.8.0/isolate.go:59 +0x44 fp=0x140005bd760 sp=0x140005bd720 pc=0x1009c74a4
rogchap.com/v8go.NewContext({0x140005bd8f8, 0x1, 0x10199dbb5?})
        /home/runner/go/pkg/mod/rogchap.com/v8go@v0.8.0/context.go:57 +0x54 fp=0x140005bd7c0 sp=0x140005bd760 pc=0x1009c53e4
github.com/plentico/plenti/cmd/build.Client({0x140001342a0, 0x6}, {0x0?})
        /home/runner/work/plenti/plenti/cmd/build/client.go:50 +0x15c fp=0x140005bda70 sp=0x140005bd7c0 pc=0x100a614bc
github.com/plentico/plenti/cmd.Build()
        /home/runner/work/plenti/plenti/cmd/build.go:145 +0x63c fp=0x140005bde40 sp=0x140005bda70 pc=0x100bff45c
github.com/plentico/plenti/cmd/serve.(*watcher).watch.func1()
        /home/runner/work/plenti/plenti/cmd/serve/watcher.go:105 +0x1b4 fp=0x140005bdfd0 sp=0x140005bde40 pc=0x100ae7744
runtime.goexit()
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/asm_arm64.s:1270 +0x4 fp=0x140005bdfd0 sp=0x140005bdfd0 pc=0x100742b04
created by github.com/plentico/plenti/cmd/serve.(*watcher).watch
        /home/runner/work/plenti/plenti/cmd/serve/watcher.go:86 +0x444

goroutine 1 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x12ac66860, 0x72)
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0x14000412980?, 0x4?, 0x0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:83 +0x2c
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0x14000412980)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_unix.go:614 +0x1d0
net.(*netFD).accept(0x14000412980)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/fd_unix.go:172 +0x28
net.(*TCPListener).accept(0x14000395b60)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/tcpsock_posix.go:139 +0x2c
net.(*TCPListener).Accept(0x14000395b60)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/tcpsock.go:288 +0x30
net/http.(*Server).Serve(0x1400040ad20, {0x102d82fc8, 0x14000395b60})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3039 +0x318
net/http.(*Server).ListenAndServe(0x1400040ad20)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:2968 +0x88
net/http.ListenAndServe(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3222
github.com/plentico/plenti/cmd.glob..func6(0x10311a600?, {0x103180b70, 0x0, 0x0})
        /home/runner/work/plenti/plenti/cmd/serve.go:136 +0x624
github.com/spf13/cobra.(*Command).execute(0x10311a600, {0x103180b70, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x10311a380)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x34c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/plentico/plenti/cmd.Execute()
        /home/runner/work/plenti/plenti/cmd/root.go:48 +0x2c
main.main()
        /home/runner/work/plenti/plenti/main.go:7 +0x20

goroutine 36 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x12ac66770, 0x72)
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0x1400018a000?, 0x14000472000?, 0x0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:83 +0x2c
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0x1400018a000, {0x14000472000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_unix.go:167 +0x1e4
net.(*netFD).Read(0x1400018a000, {0x14000472000?, 0x14000013668?, 0x100989fe0?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/fd_posix.go:55 +0x2c
net.(*conn).Read(0x14000010010, {0x14000472000?, 0x140000137a0?, 0x100952734?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/net.go:183 +0x38
net/http.(*connReader).Read(0x14000418960, {0x14000472000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:780 +0x248
bufio.(*Reader).fill(0x14000416a20)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:106 +0x100
bufio.(*Reader).ReadSlice(0x14000416a20, 0x0?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:371 +0x34
bufio.(*Reader).ReadLine(0x14000416a20)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:400 +0x28
net/textproto.(*Reader).readLineSlice(0x140002b9c20)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/textproto/reader.go:57 +0x78
net/textproto.(*Reader).ReadLine(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/textproto/reader.go:38
net/http.readRequest(0x14000010010?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/request.go:1029 +0x58
net/http.(*conn).readRequest(0x140001e20a0, {0x102d83748, 0x14000497640})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:988 +0x1ec
net/http.(*conn).serve(0x140001e20a0, {0x102d837f0, 0x140004186f0})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1891 +0x2f0
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x450

goroutine 8 [syscall]:
syscall.syscall6(0x4?, 0x1400050bd00?, 0x2?, 0x0?, 0x0?, 0x0?, 0x2?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/sys_darwin.go:45 +0x64
golang.org/x/sys/unix.kevent(0x0?, 0x0?, 0x57f3cd57?, 0x1b42081a6ab5?, 0x1400050bdc4?, 0x100ae63b8?)
        /home/runner/go/pkg/mod/golang.org/x/sys@v0.5.0/unix/zsyscall_darwin_arm64.go:276 +0x5c
golang.org/x/sys/unix.Kevent(0x0?, {0x0?, 0x0?, 0x1007257c0?}, {0x1400050be68?, 0x100ae5310?, 0x2?}, 0x1400050bdc4?)
        /home/runner/go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall_bsd.go:399 +0x44
github.com/fsnotify/fsnotify.read(0x1400050be28?, {0x1400050be68?, 0xa2?, 0xa}, 0x103180d30?)
        /home/runner/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:525 +0x48
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0x14000416c00)
        /home/runner/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:288 +0x78
created by github.com/fsnotify/fsnotify.NewWatcher
        /home/runner/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:63 +0x1ac

goroutine 9 [chan receive, 3 minutes]:
github.com/plentico/plenti/cmd/serve.(*watcher).watch(0x14000130020, {0x140000388d8, 0x6}, 0x102d7a558)
        /home/runner/work/plenti/plenti/cmd/serve/watcher.go:156 +0x450
github.com/plentico/plenti/cmd/serve.Gowatch.func1()
        /home/runner/work/plenti/plenti/cmd/serve/watcher.go:37 +0xac
created by github.com/plentico/plenti/cmd/serve.Gowatch
        /home/runner/work/plenti/plenti/cmd/serve/watcher.go:33 +0x108

goroutine 10 [syscall]:
syscall.syscall6(0x4?, 0x14000086d00?, 0x2?, 0x2?, 0x0?, 0x0?, 0x2?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/sys_darwin.go:45 +0x64
golang.org/x/sys/unix.kevent(0x0?, 0x0?, 0x0?, 0x0?, 0x14000086dc4?, 0x0?)
        /home/runner/go/pkg/mod/golang.org/x/sys@v0.5.0/unix/zsyscall_darwin_arm64.go:276 +0x5c
golang.org/x/sys/unix.Kevent(0x0?, {0x0?, 0x0?, 0x1007257c0?}, {0x14000086e68?, 0x100ae5310?, 0x2?}, 0x14000086dc4?)
        /home/runner/go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall_bsd.go:399 +0x44
github.com/fsnotify/fsnotify.read(0x14000086e28?, {0x14000086e68?, 0xa3?, 0xa}, 0x103180d30?)
        /home/runner/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:525 +0x48
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0x14000416c60)
        /home/runner/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:288 +0x78
created by github.com/fsnotify/fsnotify.NewWatcher
        /home/runner/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.4/kqueue.go:63 +0x1ac

goroutine 11 [chan receive, 3 minutes]:
github.com/plentico/plenti/cmd/serve.(*watcher).watch(0x14000456000, {0x140000388d8, 0x6}, 0x102d7a558)
        /home/runner/work/plenti/plenti/cmd/serve/watcher.go:156 +0x450
github.com/plentico/plenti/cmd/serve.Gowatch.func1()
        /home/runner/work/plenti/plenti/cmd/serve/watcher.go:37 +0xac
created by github.com/plentico/plenti/cmd/serve.Gowatch
        /home/runner/work/plenti/plenti/cmd/serve/watcher.go:33 +0x108

goroutine 12 [select]:
github.com/plentico/plenti/cmd/serve.(*watcher).watch.func1()
        /home/runner/work/plenti/plenti/cmd/serve/watcher.go:88 +0xc8
created by github.com/plentico/plenti/cmd/serve.(*watcher).watch
        /home/runner/work/plenti/plenti/cmd/serve/watcher.go:86 +0x444

goroutine 37 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x12ac66680, 0x72)
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0x1400018a080?, 0x140000ff000?, 0x0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:83 +0x2c
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0x1400018a080, {0x140000ff000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_unix.go:167 +0x1e4
net.(*netFD).Read(0x1400018a080, {0x140000ff000?, 0x14000017668?, 0x100989fe0?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/fd_posix.go:55 +0x2c
net.(*conn).Read(0x14000010018, {0x140000ff000?, 0x140000177a0?, 0x100952734?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/net.go:183 +0x38
net/http.(*connReader).Read(0x1400048a120, {0x140000ff000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:780 +0x248
bufio.(*Reader).fill(0x1400051c060)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:106 +0x100
bufio.(*Reader).ReadSlice(0x1400051c060, 0x0?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:371 +0x34
bufio.(*Reader).ReadLine(0x1400051c060)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:400 +0x28
net/textproto.(*Reader).readLineSlice(0x1400048a180)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/textproto/reader.go:57 +0x78
net/textproto.(*Reader).ReadLine(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/textproto/reader.go:38
net/http.readRequest(0x14000010018?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/request.go:1029 +0x58
net/http.(*conn).readRequest(0x140001e21e0, {0x102d83748, 0x14000512040})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:988 +0x1ec
net/http.(*conn).serve(0x140001e21e0, {0x102d837f0, 0x140004186f0})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1891 +0x2f0
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x450

goroutine 16 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x12ac66590, 0x72)
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0x14000412c00?, 0x140002ce000?, 0x0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:83 +0x2c
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0x14000412c00, {0x140002ce000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_unix.go:167 +0x1e4
net.(*netFD).Read(0x14000412c00, {0x140002ce000?, 0x14000019668?, 0x100989fe0?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/fd_posix.go:55 +0x2c
net.(*conn).Read(0x14000130f30, {0x140002ce000?, 0x140000197a0?, 0x100952734?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/net.go:183 +0x38
net/http.(*connReader).Read(0x140002b9b00, {0x140002ce000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:780 +0x248
bufio.(*Reader).fill(0x140000fbec0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:106 +0x100
bufio.(*Reader).ReadSlice(0x140000fbec0, 0x0?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:371 +0x34
bufio.(*Reader).ReadLine(0x140000fbec0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:400 +0x28
net/textproto.(*Reader).readLineSlice(0x140002b9b30)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/textproto/reader.go:57 +0x78
net/textproto.(*Reader).ReadLine(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/textproto/reader.go:38
net/http.readRequest(0x14000130f30?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/request.go:1029 +0x58
net/http.(*conn).readRequest(0x140001e2960, {0x102d83748, 0x14000496d40})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:988 +0x1ec
net/http.(*conn).serve(0x140001e2960, {0x102d837f0, 0x140004186f0})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1891 +0x2f0
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x450

goroutine 66 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x12ac664a0, 0x72)
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0x14000412d00?, 0x140002d0000?, 0x0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:83 +0x2c
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0x14000412d00, {0x140002d0000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_unix.go:167 +0x1e4
net.(*netFD).Read(0x14000412d00, {0x140002d0000?, 0x140004ef668?, 0x100989fe0?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/fd_posix.go:55 +0x2c
net.(*conn).Read(0x14000130f38, {0x140002d0000?, 0x140004ef7a0?, 0x100952734?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/net.go:183 +0x38
net/http.(*connReader).Read(0x140002b9bf0, {0x140002d0000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:780 +0x248
bufio.(*Reader).fill(0x140000fbf20)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:106 +0x100
bufio.(*Reader).ReadSlice(0x140000fbf20, 0x0?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:371 +0x34
bufio.(*Reader).ReadLine(0x140000fbf20)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:400 +0x28
net/textproto.(*Reader).readLineSlice(0x1400048a1b0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/textproto/reader.go:57 +0x78
net/textproto.(*Reader).ReadLine(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/textproto/reader.go:38
net/http.readRequest(0x14000130f38?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/request.go:1029 +0x58
net/http.(*conn).readRequest(0x140001e2f00, {0x102d83748, 0x14000496e00})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:988 +0x1ec
net/http.(*conn).serve(0x140001e2f00, {0x102d837f0, 0x140004186f0})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1891 +0x2f0
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x450

goroutine 38 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x12ac663b0, 0x72)
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0x140003cc000?, 0x140003f8000?, 0x0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:83 +0x2c
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0x140003cc000, {0x140003f8000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_unix.go:167 +0x1e4
net.(*netFD).Read(0x140003cc000, {0x140003f8000?, 0x140002e5668?, 0x100989fe0?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/fd_posix.go:55 +0x2c
net.(*conn).Read(0x140003d2000, {0x140003f8000?, 0x140002e57a0?, 0x100952734?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/net.go:183 +0x38
net/http.(*connReader).Read(0x140003ce090, {0x140003f8000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:780 +0x248
bufio.(*Reader).fill(0x140003f6000)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:106 +0x100
bufio.(*Reader).ReadSlice(0x140003f6000, 0x0?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:371 +0x34
bufio.(*Reader).ReadLine(0x140003f6000)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:400 +0x28
net/textproto.(*Reader).readLineSlice(0x140003ce0c0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/textproto/reader.go:57 +0x78
net/textproto.(*Reader).ReadLine(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/textproto/reader.go:38
net/http.readRequest(0x140003d2000?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/request.go:1029 +0x58
net/http.(*conn).readRequest(0x1400013e280, {0x102d83748, 0x1400020e080})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:988 +0x1ec
net/http.(*conn).serve(0x1400013e280, {0x102d837f0, 0x140004186f0})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1891 +0x2f0
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x450

goroutine 67 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x12ac662c0, 0x72)
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0x14000412d80?, 0x140002d2000?, 0x0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:83 +0x2c
internal/poll.(*pollDesc).waitRead(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0x14000412d80, {0x140002d2000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_unix.go:167 +0x1e4
net.(*netFD).Read(0x14000412d80, {0x140002d2000?, 0x14000015668?, 0x100989fe0?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/fd_posix.go:55 +0x2c
net.(*conn).Read(0x14000130f40, {0x140002d2000?, 0x140000157a0?, 0x100952734?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/net.go:183 +0x38
net/http.(*connReader).Read(0x140002b9ce0, {0x140002d2000, 0x1000, 0x1000})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:780 +0x248
bufio.(*Reader).fill(0x140000fbf80)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:106 +0x100
bufio.(*Reader).ReadSlice(0x140000fbf80, 0x0?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:371 +0x34
bufio.(*Reader).ReadLine(0x140000fbf80)
        /opt/hostedtoolcache/go/1.18.10/x64/src/bufio/bufio.go:400 +0x28
net/textproto.(*Reader).readLineSlice(0x140002b9d10)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/textproto/reader.go:57 +0x78
net/textproto.(*Reader).ReadLine(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/textproto/reader.go:38
net/http.readRequest(0x14000130f40?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/request.go:1029 +0x58
net/http.(*conn).readRequest(0x140001e2fa0, {0x102d83748, 0x14000496ec0})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:988 +0x1ec
net/http.(*conn).serve(0x140001e2fa0, {0x102d837f0, 0x140004186f0})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:1891 +0x2f0
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/server.go:3071 +0x450

r0      0x3a
r1      0x0
r2      0x120a8
r3      0x17000d002
r4      0x102b458d5
r5      0x17000d520
r6      0xa
r7      0x1dc46a978
r8      0x1
r9      0x1dc471b20
r10     0x2
r11     0xfffffffd
r12     0x10000000000
r13     0x0
r14     0x0
r15     0x0
r16     0x1834d7454
r17     0x1dd631968
r18     0x0
r19     0x140ae5552
r20     0x1
r21     0x140ad8000
r22     0x140ae4250
r23     0x170015c18
r24     0x170015cfe
r25     0x17000d568
r26     0x0
r27     0x1031900bb
r28     0x140ae64d8
r29     0x17000d510
lr      0x100c37150
sp      0x17000d510
pc      0x100c28364
fault   0x100c28364
```

</details>

<details><summary>Second crash log </summary>

```terminal
Total build took 1.265203625s
Compiling client SPA with Svelte took 1.151195958s
Creating data_source took 3.064125ms
Running Gopack took 101.625µs
2023/04/22 09:13:42 build.go:159: 
Error in Gopack main.js build step
Can't runPack on public/spa/core/router.js";import allContent from"../generated/content.js";import*as allLayouts from"../generated/layouts.js";import{env}from"../generated/env.js";let content=allContent.find(e=>e.filepath===document.documentElement.dataset.contentFilepath),path=location.pathname,params=new URLSearchParams(location.search);import("../layouts/content/"+content.type+".js 
Could not read file public/spa/core/router.js";import allContent from"../generated/content.js";import*as allLayouts from"../generated/layouts.js";import{env}from"../generated/env.js";let content=allContent.find(e=>e.filepath===document.documentElement.dataset.contentFilepath),path=location.pathname,params=new URLSearchParams(location.search);import("../layouts/content/"+content.type+".js to convert to esm
open public/spa/core/router.js";import allContent from"../generated/content.js";import*as allLayouts from"../generated/layouts.js";import{env}from"../generated/env.js";let content=allContent.find(e=>e.filepath===document.documentElement.dataset.contentFilepath),path=location.pathname,params=new URLSearchParams(location.search);import("../layouts/content/"+content.type+".js: no such file or directory
```

</details>

In both instances, I was able to re-start and serve the site again.

Hope that helps. Let me know if I can help with anything.

Cheers,
Ben

**Comment by jimafisk** [comment]
Thanks for the bug report @jamestagal! I've been seeing some crashes on various projects on my end as well, but they don't happen very often. It's something I've been meaning to look into!
